base_locale: es
locales: [en, es, ca]
data:
  read:
    - config/locales/**/%{locale}.yml
    - config/locales/**/*/%{locale}.yml
    - vendor/auth_strategies/**/config/locales/**/%{locale}.yml
    - vendor/auth_strategies/**/config/locales/**/*/%{locale}.yml
    - vendor/gobierto_engines/custom-fields-data-grid-plugin/config/locales/**/*/%{locale}.yml
search:
  paths:
    - app/
    - vendor/auth_strategies/
    - vendor/gobierto_engines/custom-fields-data-grid-plugin/
  exclude:
    - app/assets/**/*
  relative_roots:
    - app/cells
    - app/controllers
    - app/helpers
    - app/mailers
    - app/presenters
    - app/views
    - vendor/auth_strategies/null_strategy/app/views
    - vendor/auth_strategies/ldap_strategy/app/views
ignore_missing:
  - 'gobierto_budgets.visualizations.*'
  - 'layouts.sandbox.*'
  - 'sandbox.*'
  - 'gobierto_observatory.cards.*'
  - 'gobierto_budgets.budgets.cards.*'
  - 'gobierto_budgets.budgets.index_old.*'
  - 'gobierto_budgets.budgets.guide.*'
  - 'gobierto_budgets.budgets_execution.metric_box_cell.*'
  - 'gobierto_budgets.invoices.show.table.fields.*'
  - 'grammatical_particles.*'
  - 'gobierto_common.visualizations.cards.*'
  - 'gobierto_common.visualizations.frequency.dailt'
  - 'gobierto_admin.gobierto_plans.projects.moderation_visibility_action.*'
  - 'gobierto_data.data_type.*'

ignore_unused:
  - 'number.*'
  - 'time.*'
  - 'errors.*'
  - 'datetime.*'
  - 'date.*'
  - 'activerecord.*'
  - 'activemodel.*'
  - 'helpers.*'
  - 'support.*'
  - 'layouts.sandbox.*'
  - 'layouts.*.application.*'
  - 'user.subscriptions.create.*_success'
  - 'gobierto_budgets.budget_lines.show.twitter_text_*'
  - 'gobierto_budgets.visualizations.G_custom'
  - 'gobierto_budgets.visualizations.I_custom'
  - 'gobierto_budgets.budgets.index.*'
  - 'gobierto_budgets.budgets_execution.*'
  - 'gobierto_budgets.invoices.show.*'
  - 'gobierto_budgets.budgets_execution.metric_box_cell.*'
  - 'gobierto_people.activities.gobierto_people_person*'
  - 'invisible_captcha.*'
  - '*.events.*'
  - 'user.census_verifications.messages.not_verified'
  - 'user.sessions.user_not_signed_in'
  - 'gobierto_budgets.budgets_elaboration.index.proposal'
  - 'gobierto_budgets.visualizations.*'
  - 'gobierto_common.visualizations.cards.*'
  - 'gobierto_common.visualizations.*'
  - 'gobierto_observatory.graphics.*'
  - 'gobierto_observatory.inhabitants'
  - 'views.pagination.*'
  - 'helpers.page_entries_info.*'
  - 'gobierto_observatory.cards.*'
  - 'gobierto_budgets.budgets.cards.*'
  - 'user.subscriptions.subscribable_button.*'
  - 'grammatical_particles.*'
  - 'gobierto_admin.gobierto_citizens_charters.charters.editions.index.*_interval'
  - 'gobierto_admin.gobierto_citizens_charters.charters.editions.index.*_period'
  - 'gobierto_admin.gobierto_citizens_charters.charters.editions_intervals.edition_interval.*_interval'
  - 'gobierto_citizens_charters.shared.*_interval'
  - 'gobierto_citizens_charters.shared.evolution.*'
  - 'gobierto_admin.gobierto_plans.plans.import_csv.defaults.*'
  - 'gobierto_admin.gobierto_plans.projects.filters_row.*_value.*'
  - 'gobierto_admin.gobierto_plans.categories.*'
  - 'gobierto_admin.gobierto_plans.projects.publish.*'
  - 'gobierto_admin.gobierto_plans.projects.unpublish.*'
  - 'gobierto_admin.gobierto_plans.admin_mailer.*.subject'
  - 'gobierto_admin.custom_fields_plugins.*'
  - 'gobierto_plans.plan_types.show.read_less'
  - 'gobierto_plans.plan_types.show.read_more'
  - 'gobierto_admin.layouts.application.modules.*'
  - 'gobierto_admin.layouts.application.global'
  - 'gobierto_data.data_type.*'
  - 'gobierto_visualizations.visualizations.categories.*'
  - 'gobierto_visualizations.visualizations.tender_statuses.*'
  - 'gobierto_visualizations.visualizations.contract_types.*'
  - 'gobierto_visualizations.visualizations.contract_statuses.*'
  - 'gobierto_visualizations.visualizations.process_types.*'
  - 'routes.*'

translation:
  api_key: ''
