base_locale: es
locales: [en, es, ca]
data:
  read:
    - config/locales/**/%{locale}.yml
    - config/locales/**/*/%{locale}.yml
ignore_missing:
  - 'gobierto_budgets.visualizations.*'
  - 'layouts.sandbox.*'
  - 'sandbox.*'
  - 'gobierto_budget_consultations.consultation_statuses.*'
  - 'gobierto_indicators.cards.*'
  - 'gobierto_budgets.budgets.index_old.*'

ignore_unused:
  - 'number.*'
  - 'time.*'
  - 'errors.*'
  - 'datetime.*'
  - 'date.*'
  - 'activerecord.*'
  - 'activemodel.*'
  - 'helpers.*'
  - 'support.*'
  - 'layouts.sandbox.*'
  - 'layouts.*.application.*'
  - 'user.subscriptions.create.*_success'
  - 'gobierto_admin.gobierto_budget_consultations.consultations.consultation_items.*_modal.*'
  - 'gobierto_budgets.budget_lines.show.twitter_text_*'
  - 'gobierto_budgets.visualizations.G_custom'
  - 'gobierto_budgets.visualizations.I_custom'
  - 'gobierto_budgets.budgets.index.*'
  - 'gobierto_budgets.budgets_execution.*'
  - 'gobierto_people.activities.gobierto_people_person*'
  - 'invisible_captcha.*'
  - '*.events.*'
  - 'gobierto_budget_consultations.consultation_statuses.*'
  - 'user.census_verifications.messages.not_verified'
  - 'gobierto_budget_consultations.consultation_statuses.*'
  - 'user.sessions.user_not_signed_in'
  - 'gobierto_budget_consultations.consultations.consultation_responses.new.user_not_signed_in_html'
  - 'views.pagination.*'
  - 'helpers.page_entries_info.*'
  - 'gobierto_indicators.cards.*'
  - 'user.subscriptions.subscribable_button.*'

translation:
  api_key: ''
